from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

title = doc.add_heading('GUIA COMPLETA DEL BUSCADOR DE BIENES SICOBIM', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_paragraph('Explicacion linea por linea - Para entender hasta un nino de 5 anos')
doc.add_paragraph('')

doc.add_heading('1. IMPORTAR HERRAMIENTAS', level=1)
doc.add_paragraph('// Linha 1: import tkinter as tk')
doc.add_paragraph('  - tkinter: Es la caja de herramientas para crear ventanas, botones, tablas')
doc.add_paragraph('  - as tk: Le damos un apodo corto para escribir menos')
doc.add_paragraph('')
doc.add_paragraph('// Linha 2: from tkinter import ttk, messagebox')
doc.add_paragraph('  - ttk: Herramientas avanzadas de tkinter (tablas, combos)')
doc.add_paragraph('  - messagebox: Ventanitas de alerta (error, ok, pregunta)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 3: import pandas as pd')
doc.add_paragraph('  - pandas: Maneja datos como Excel dentro del codigo')
doc.add_paragraph('  - as pd: Apodo corto')
doc.add_paragraph('')
doc.add_paragraph('// Linha 4: import os')
doc.add_paragraph('  - os: Maneja archivos y carpetas (crear, borrar, buscar)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 5: import sys')
doc.add_paragraph('  - sys: Herramientas del sistema (donde esta el programa, argumentos)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 6: import logging')
doc.add_paragraph('  - logging: Escribe un diario de lo que hace el programa')
doc.add_paragraph('')
doc.add_paragraph('// Linha 7: from datetime import datetime')
doc.add_paragraph('  - datetime: Para saber la hora y fecha actual')

doc.add_heading('2. CONFIGURACION DEL PROGRAMA', level=1)
doc.add_paragraph('// Linha 9-12: if getattr(sys, frozen, False)')
doc.add_paragraph('  - Detecta si el programa esta compiled (exe) o solo codigo')
doc.add_paragraph('  - sys.frozen = True cuando es un .exe')
doc.add_paragraph('  - BASE_DIR = Donde esta instalado el programa')
doc.add_paragraph('')
doc.add_paragraph('// Linha 14: LOG_FILE = os.path.join(BASE_DIR, "bienes.log")')
doc.add_paragraph('  - Donde guardaremos el diario (bienes.log)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 16-22: logging.basicConfig')
doc.add_paragraph('  - Configura como escribira el diario')
doc.add_paragraph('  - level=INFO: Escribe todo tipo de mensajes')
doc.add_paragraph('  - format: Como se ve cada entrada (fecha - tipo - mensaje)')
doc.add_paragraph('  - FileHandler: Guarda en archivo (no en pantalla)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 25-28: EXCEL_FILES = [...]')
doc.add_paragraph('  - Lista de archivos Excel que puede usar')
doc.add_paragraph('  - El programa buscara el primero que exista')
doc.add_paragraph('')
doc.add_paragraph('// Linha 30-35: def encontrar_excel()')
doc.add_paragraph('  - Funcion que busca el archivo Excel')
doc.add_paragraph('  - Recorre la lista de archivos')
doc.add_paragraph('  - Devuelve la ruta del primero que encuentra')
doc.add_paragraph('')
doc.add_paragraph('// Linha 37: EXCEL_PATH = encontrar_excel()')
doc.add_paragraph('  - Se ejecuta la funcion y guarda el resultado')

doc.add_heading('3. FUNCION PARA ESCRIBIR EN EL LOG', level=1)
doc.add_paragraph('// Linha 39-40: def log_accion(accion, detalles="")')
doc.add_paragraph('  - Funcion pequena para escribir en el diario')
doc.add_paragraph('  - accion: Que paso发生了什么 (ej: BUSQUEDA, BAJA)')
doc.add_paragraph('  - detalles: Informacion extra')
doc.add_paragraph('  - logger.info: Escribe en el archivo de diario')

doc.add_heading('4. CLASE PRINCIPAL - __init__', level=1)
doc.add_paragraph('// Linha 42: class BuscadorBienes:')
doc.add_paragraph('  - class: Plantilla para crear objetos')
doc.add_paragraph('  - BuscadorBienes: Nombre de la clase')
doc.add_paragraph('')
doc.add_paragraph('// Linha 43: def __init__(self, root):')
doc.add_paragraph('  - __init__: Se ejecuta cuando creamos un objeto')
doc.add_paragraph('  - root: La ventana principal de Tkinter')
doc.add_paragraph('')
doc.add_paragraph('// Linha 44: self.root = root')
doc.add_paragraph('  - Guardamos la ventana en una variable')
doc.add_paragraph('')
doc.add_paragraph('// Linha 45: self.root.title("...")')
doc.add_paragraph('  - Pone el titulo en la pestana de la ventana')
doc.add_paragraph('')
doc.add_paragraph('// Linha 46: self.root.geometry("1200x700")')
doc.add_paragraph('  - Tamano inicial: 1200px ancho, 700px alto')
doc.add_paragraph('')
doc.add_paragraph('// Linha 47: self.root.minsize(900, 500)')
doc.add_paragraph('  - Tamano minimo: no se puede hacer mas pequena')
doc.add_paragraph('')
doc.add_paragraph('// Linha 48: self.root.configure(bg="#1e1e2e")')
doc.add_paragraph('  - Color de fondo: azul oscuro (formato hexadecimal)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 50: self.df = self.cargar_datos()')
doc.add_paragraph('  - Llama la funcion para leer el Excel')
doc.add_paragraph('  - Guarda los datos en self.df (la tabla en memoria)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 52-53: self.configurar_estilos()')
doc.add_paragraph('  - Configura los colores de la tabla')
doc.add_paragraph('')
doc.add_paragraph('// Linha 53: self.crear_interfaz()')
doc.add_paragraph('  - Dibuja todos los botones, campos, tablas')
doc.add_paragraph('')
doc.add_paragraph('// Linha 55: self.root.bind(...)')
doc.add_paragraph('  - Configura que pasa cuando se mueve la ventana')

doc.add_heading('5. CARGAR DATOS DEL EXCEL', level=1)
doc.add_paragraph('// Linha 57: def cargar_datos(self):')
doc.add_paragraph('  - Funcion que lee el archivo Excel')
doc.add_paragraph('')
doc.add_paragraph('// Linha 58-59: try: / import numpy as np')
doc.add_paragraph('  - try: Intentamos hacer algo que puede fallar')
doc.add_paragraph('  - numpy: Herramienta para manejar numeros especiales')
doc.add_paragraph('')
doc.add_paragraph('// Linha 60: log_accion("INICIO", ...)')
doc.add_paragraph('  - Escribimos en el diario que empezamos')
doc.add_paragraph('')
doc.add_paragraph('// Linha 61: pd.read_excel(EXCEL_PATH, header=0, engine=openpyxl)')
doc.add_paragraph('  - Lee el archivo Excel')
doc.add_paragraph('  - header=0: La primera fila es el titulo')
doc.add_paragraph('  - engine=openpyxl: Como leer el archivo Excel')
doc.add_paragraph('')
doc.add_paragraph('// Linha 62: df.columns = df.columns.str.strip()')
doc.add_paragraph('  - Limpia espacios al inicio y fin de los nombres de columnas')
doc.add_paragraph('')
doc.add_paragraph('// Linha 64: df = df.loc[:, ~df.columns.isna()]')
doc.add_paragraph('  - Elimina columnas vacias (NaN)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 66-69: for col in df.columns')
doc.add_paragraph('  - Busca la columna de INVENTARIO')
doc.add_paragraph('  - Convierte los valores a numeros enteros')
doc.add_paragraph('')
doc.add_paragraph('// Linha 71-73: for col in df.columns')
doc.add_paragraph('  - Convierte todas las columnas de texto a string')
doc.add_paragraph('  - Limpia espacios')
doc.add_paragraph('')
doc.add_paragraph('// Linha 75-78: if STATUS not in df.columns')
doc.add_paragraph('  - Si no existe la columna STATUS')
doc.add_paragraph('  - La crea con valor 1 por defecto')
doc.add_paragraph('  - Guarda el Excel actualizado')
doc.add_paragraph('')
doc.add_paragraph('// Linha 80: log_accion("CARGA_EXITO", ...)')
doc.add_paragraph('  - Escribe en el diario que salio bien')
doc.add_paragraph('')
doc.add_paragraph('// Linha 81: return df')
doc.add_paragraph('  - Devuelve la tabla con los datos')
doc.add_paragraph('')
doc.add_paragraph('// Linha 82-84: except Exception as e:')
doc.add_paragraph('  - Si algo salio mal')
doc.add_paragraph('  - Muestra ventana de error')
doc.add_paragraph('  - Devuelve una tabla vacia')

doc.add_heading('6. ENCONTRAR COLUMNA', level=1)
doc.add_paragraph('// Linha 87-91: def encontrar_columna(self, nombre_buscar)')
doc.add_paragraph('  - Busca una columna por su nombre')
doc.add_paragraph('  - Ejemplo: buscar "INVENTARIO" encuentra "N INVENTARIO"')
doc.add_paragraph('  - Devuelve el nombre exacto de la columna')

doc.add_heading('7. CONFIGURAR ESTILOS', level=1)
doc.add_paragraph('// Linha 93-109: def configurar_estilos(self)')
doc.add_paragraph('  - Configura el aspecto visual de la tabla')
doc.add_paragraph('  - Treeview: La tabla donde se ven los resultados')
doc.add_paragraph('  - Colors: fondo oscuro, texto claro')
doc.add_paragraph('  - rowheight: Altura de cada fila')

doc.add_heading('8. CREAR INTERFAZ GRAFICA', level=1)
doc.add_paragraph('// Linha 111-114: header_frame')
doc.add_paragraph('  - Frame = Contenedor (como una caja)')
doc.add_paragraph('  - bg=#1e1e2e: Color de fondo')
doc.add_paragraph('  - pack: Organiza el frame en la ventana')
doc.add_paragraph('')
doc.add_paragraph('// Linha 115-119: title')
doc.add_paragraph('  - Label = Etiqueta con texto')
doc.add_paragraph('  - text: El texto a mostrar')
doc.add_paragraph('  - font: Tipo y tamano de letra')
doc.add_paragraph('  - fg: Color del texto (foreground)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 121-125: subtitle')
doc.add_paragraph('  - Segundo texto mas pequeno')
doc.add_paragraph('')
doc.add_paragraph('// Linha 127-128: search_frame')
doc.add_paragraph('  - Contenedor para la barra de busqueda')
doc.add_paragraph('')
doc.add_paragraph('// Linha 130-132: Label "Buscar:"')
doc.add_paragraph('  - Etiqueta que dice "Buscar:"')
doc.add_paragraph('')
doc.add_paragraph('// Linha 134-142: entry_busqueda')
doc.add_paragraph('  - Entry = Caja donde el usuario escribe')
doc.add_paragraph('  - StringVar: Variable que guarda lo que se escribe')
doc.add_paragraph('  - width=40: Ancho del campo')
doc.add_paragraph('')
doc.add_paragraph('// Linha 144-152: btn_buscar')
doc.add_paragraph('  - Button = Boton que se puede presionar')
doc.add_paragraph('  - command=self.buscar: Funcion a ejecutar al hacer clic')
doc.add_paragraph('  - bg=#89b4fa: Color de fondo del boton')
doc.add_paragraph('')
doc.add_paragraph('// Linha 154-162: btn_limpiar')
doc.add_paragraph('  - Boton para borrar lo escrito y mostrar todo')
doc.add_paragraph('')
doc.add_paragraph('// Linha 164-176: filtro_status')
doc.add_paragraph('  - Combobox = Menu desplegable')
doc.add_paragraph('  - values: Lista de opciones [VIGENTES, BAJAS, TODOS]')
doc.add_paragraph('  - state=readonly: No permite escribir, solo elegir')
doc.add_paragraph('  - bind: Ejecuta buscar() cuando cambia la seleccion')
doc.add_paragraph('')
doc.add_paragraph('// Linha 178-189: campo_busqueda')
doc.add_paragraph('  - Menu para elegir DONDE buscar')
doc.add_paragraph('  - Todos, Descripcion, Ubicacion, Inventario, etc.')
doc.add_paragraph('')
doc.add_paragraph('// Linha 193-214: tree (Treeview)')
doc.add_paragraph('  - La tabla principal donde se ven los bienes')
doc.add_paragraph('  - columns: Columnas a mostrar')
doc.add_paragraph('  - headings: Titulos de las columnas')
doc.add_paragraph('  - scrollbar: Barra para desplazamiento')
doc.add_paragraph('  - bind: Doble clic abre el detalle')

doc.add_heading('9. FUNCION BUSCAR', level=1)
doc.add_paragraph('// Linha 243-246: Obtener valores')
doc.add_paragraph('  - buscar_var.get(): Lo que escribio el usuario')
doc.add_paragraph('  - campo_busqueda.get(): Donde buscar')
doc.add_paragraph('  - filtro_status.get(): Filtro (VIGENTES/BAJAS/TODOS)')
doc.add_paragraph('')
doc.add_paragraph('// Linha 249-254: Aplicar filtro')
doc.add_paragraph('  - df[df[STATUS]==1]: Solo vigentes (STATUS=1)')
doc.add_paragraph('  - df[df[STATUS]==0]: Solo bajas (STATUS=0)')
doc.add_paragraph('  - df.copy(): Copia para no modificar el original')
doc.add_paragraph('')
doc.add_paragraph('// Linha 256-259: Si no hay criterio')
doc.add_paragraph('  - Muestra todo el dataframe filtrado')
doc.add_paragraph('')
doc.add_paragraph('// Linha 263-267: Busqueda')
doc.add_paragraph('  - Si campo=Todos: Busca en todas las columnas')
doc.add_paragraph('  - Si no: Busca solo en la columna elegida')
doc.add_paragraph('  - str.contains: Busca el texto dentro')
doc.add_paragraph('')
doc.add_paragraph('// Linha 269-279: Mostrar resultados')
doc.add_paragraph('  - Si hay resultados: Llena la tabla')
doc.add_paragraph('  - Si no hay: Muestra mensaje de error')

doc.add_heading('10. LLENAR TABLA', level=1)
doc.add_paragraph('// Linha 301-323: def llenar_tabla(self, df)')
doc.add_paragraph('  - Borra todo lo que hay en la tabla')
doc.add_paragraph('  - Para cada fila del dataframe:')
doc.add_paragraph('    - Obtiene: Inventario, Descripcion, Ubicacion, Estado, Importe')
doc.add_paragraph('    - Inserta una fila en la tabla')
doc.add_paragraph('    - tags: Guarda el indice para poder editar despues')

doc.add_heading('11. MOSTRAR DETALLE', level=1)
doc.add_paragraph('// Linha 325-331: Obtener seleccion')
doc.add_paragraph('  - tree.selection(): Que fila selected')
doc.add_paragraph('  - tree.item(): Los datos de esa fila')
doc.add_paragraph('  - tags: El indice en el dataframe')
doc.add_paragraph('')
doc.add_paragraph('// Linha 333: df.iloc[idx]')
doc.add_paragraph('  - Obtiene todos los datos del bien seleccionado')
doc.add_paragraph('')
doc.add_paragraph('// Linha 336-344: Nueva ventana')
doc.add_paragraph('  - Toplevel: Nueva ventana sobre la principal')
doc.add_paragraph('  - Canvas + Scrollbar: Para mover si es muy largo')
doc.add_paragraph('')
doc.add_paragraph('// Linha 372-399: Campos a mostrar')
doc.add_paragraph('  - Lista de campos con su nombre')
doc.add_paragraph('  - editable: Si el usuario puede cambiarlo')
doc.add_paragraph('')
doc.add_paragraph('// Linha 429-438: Entry (campo editable)')
doc.add_paragraph('  - Si el campo es editable, crea un Entry')
doc.add_paragraph('  - Guarda la entrada en un diccionario')
doc.add_paragraph('')
doc.add_paragraph('// Linha 440-454: Label (campo no editable)')
doc.add_paragraph('  - Si no es editable, solo muestra el valor')
doc.add_paragraph('  - Cambia color segun el estado (bueno=verde, malo=rojo)')

doc.add_heading('12. GUARDAR CAMBIOS', level=1)
doc.add_paragraph('// Linha 456-475: def guardar_cambios()')
doc.add_paragraph('  - Recorre todas las entradas editables')
doc.add_paragraph('  - Guarda los nuevos valores en el dataframe')
doc.add_paragraph('  - df.to_excel(): Guarda el Excel actualizado')
doc.add_paragraph('  - Muestra mensaje de exito')

doc.add_heading('13. DAR DE BAJA', level=1)
doc.add_paragraph('// Linha 477-492: def dar_de_baja()')
doc.add_paragraph('  - Pide confirmacion (messagebox.askyesno)')
doc.add_paragraph('  - Cambia STATUS a 0 (borrado logico)')
doc.add_paragraph('  - Guarda el Excel')

doc.add_heading('14. CRUZAR POR INVENTARIO', level=1)
doc.add_paragraph('// Linha 535-562: def cruzar_inventario(self)')
doc.add_paragraph('  - Busca archivo en: archivo_cruzar/ARCHIVO_NUEVO.xlsx')
doc.add_paragraph('  - Lee ambos Excel (base y nuevo)')
doc.add_paragraph('  - Convierte inventario a string sin espacios')
doc.add_paragraph('  - Crea conjuntos de inventarios unicos')
doc.add_paragraph('  - Existentes: Los que estan en ambos')
doc.add_paragraph('  - Faltantes: Los que solo estan en nuevo')
doc.add_paragraph('  - Genera Excel con 2 hojas')
doc.add_paragraph('  - Abre el archivo automaticamente')

doc.add_heading('15. CRUZAR POR INVENTARIO + CABM', level=1)
doc.add_paragraph('// Linha 564-611: def cruzar_inv_cabm(self)')
doc.add_paragraph('  - Igual que el anterior pero con 2 condiciones')
doc.add_paragraph('  - CLAVE_CRUEZE = INVENTARIO + CABM')
doc.add_paragraph('  - Solo hace match si ambos coinciden')
doc.add_paragraph('  - Es mas estricto')

doc.add_heading('16. BOTONES EN INTERFAZ', level=1)
doc.add_paragraph('// Linha 126-142: btn_cruzar_frame')
doc.add_paragraph('  - Frame donde van los botones de cruze')
doc.add_paragraph('')
doc.add_paragraph('// Linha 128-137: btn_cruzar_inv')
doc.add_paragraph('  - Boton amarillo: Cruzar solo por Inventario')
doc.add_paragraph('  - command=self.cruzar_inventario')
doc.add_paragraph('')
doc.add_paragraph('// Linha 139-148: btn_cruzar_inv_cabm')
doc.add_paragraph('  - Boton verde: Cruzar por Inventario + CABM')
doc.add_paragraph('  - command=self.cruzar_inv_cabm')

doc.add_heading('17. FUNCION MAIN', level=1)
doc.add_paragraph('// Linha 534-537: def main()')
doc.add_paragraph('  - Crea la ventana de Tkinter')
doc.add_paragraph('  - Crea el objeto BuscadorBienes')
doc.add_paragraph('  - Inicia el ciclo de eventos (root.mainloop())')

doc.add_heading('18. EJECUTAR PROGRAMA', level=1)
doc.add_paragraph('// Linha 539-540: if __name__ == main:')
doc.add_paragraph('  - Si ejecutamos este archivo directamente')
doc.add_paragraph('  - Llama a main()')
doc.add_paragraph('  - No se ejecuta si importamos este archivo')

doc.add_heading('RESUMEN DE FRAMEWORKS', level=1)
doc.add_paragraph('TKINTER: Crea la ventana, botones, tablas (interfaz grafica)')
doc.add_paragraph('PANDAS: Lee y manipula datos como Excel en memoria')
doc.add_paragraph('OPENPYXL: Guarda archivos en formato Excel')
doc.add_paragraph('PYTHON: El lenguaje de programacion')

doc.add_heading('CREDITOS', level=1)
doc.add_paragraph('Desarrollado por: Ing. Miguel Angel Ramirez Galicia')
doc.add_paragraph('Para: ISSSTE - SICOBIM')
doc.add_paragraph('Fecha: 2025')

doc.save('C:/bienes-python/GUIA_COMPLETA_BUSCADOR_BIENES.docx')
print('Word creado con codigo linea por linea!')